# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_grace_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='extensions_used',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
