# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='grading_started',
            field=models.BooleanField(default=False),
        ),
    ]
