# Generated by Django 2.2.7 on 2020-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_python3+django2_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='expected_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='gradescope_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='gradescope_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gradescope_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
